# --- Configuration de la Base de Données Principale (SQL Server) ---

spring:
  application:
    name: Kobus v2
  datasource:
    primary:
      jdbcUrl: jdbc:sqlserver://localhost:1433;databaseName=VIE_CAMEROUN_EXT_TEST_CLI_UNIQ_V2;encrypt=true;trustServerCertificate=true;
      # jdbcUrl: jdbc:sqlserver://DEV-DSK-C010:1433;databaseName=VIE_CAMEROUN_EXT_TEST_CLI_UNIQ_V2;encrypt=true;trustServerCertificate=true;
      username: aka
      password: azertyuio
      # username: solosolo
      # password: "23AL86196$"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbcDialect: SQLServer2012Dialect
      hikari:
        pool-name: PrimaryConnexionPool
        maximum-pool-size: 100000
        connection-timeout: 30000
        idle-timeout: 600000 # 10 minutes
        max-lifetime: 1800000 # 30 minutes

    secondary:
      jdbcUrl: jdbc:sqlserver://localhost:1433;databaseName=DWH_SUNSHINE;encrypt=true;trustServerCertificate=true;
      username: aka
      password: azertyuio
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbcDialect: SQLServer2012Dialect
      hikari:
        pool-name: SecondaryConnexionPool
        maximum-pool-size: 100000
        connection-timeout: 30000
        idle-timeout: 600000 # 10 minutes
        max-lifetime: 1800000 # 30 minutes

  app:
    jwt:
      secret: K!z8E^a7@wP1$N#3sG2tFv*YqLzRbUeM
      expiration-in-ms: 7200000

  mail:
    host: smtp.gmail.com
    port: 587
    username: sguira96@gmail.com
    password: "fffu vgcy mcwa yzjl"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
